### ISSUE TITLE
AI Issue

### ISSUE THREAD

**Issue by Hydra84034** [10cl/chatdev#19]
Hello,
I just installed the extension onto Chrome and started the simulation but I keep getting an error.
It keeps telling me this "Failed to establish websocket connection."
How do I fix?

I want to use Falcon and/or Vicuna

**Comment by 10cl** [comment]
Which LLM did you choose, select the llm website you have already logged in to and then use it

**Comment by Hydra84034** [comment]
I could not find the site for either model I mentioned before. Do those models even have their own sites or no?

Also, I have Falcon running on my own computer. Is it possible to use it instead?

**Comment by 10cl** [comment]
try this https://chat.lmsys.org/, vicuna、chatglm、llama、wizardlm、falcon、mistral  depend on this website and I will mark it later.

**Comment by Hydra84034** [comment]
It's working now. Thank you
