### ISSUE TITLE
玩家作为一个非 Agent 角色，本身也可以与 Agent 进行互动，譬如和 Agent 进行对话，Agent 会根据自己的设定对玩家进行回复我想知道想实现这部分功能的代码有哪些可以说下位置在哪么

### ISSUE THREAD

**Issue by 2642543078** [10cl/chatdev#20]

**Comment by 2642543078** [comment]
The functionality of this part is the front end and the back end where is the front end code where is the back end code how is the front end connected to the back end

**Comment by 10cl** [comment]
我在 generative_agents 看到你也刷了很多ISSUE，看起来你对Github不太熟悉，并且有很多疑问，可以整理一下你的背景和你想了解的内容发送到我的邮箱，我会给你解答，谢谢

**Comment by 2642543078** [comment]
您好，我的背景就是一个nlp算法工程师 我只懂nlp的内容就是想要实现这样功能 我并不懂后端和前端怎么进行连接起来 地图我已经修改了角色也已经修改过了 现在就是想要实现一个玩家进去和agent进行交互 但是您所开源的项目不是python写的 所以不是很懂那个语音 所以只能借鉴你的项目的位置在哪 然后去复现
我现在所作的就是&nbsp;generative_agents 现在我就是想要在这个项目的基础上实现我所说的功能 就是玩家作为一个非agent角色 本身想要跟agent进行互动，对agent进行对话 就是你项目所实现的那种效果。确实我在&nbsp;generative_agents上发了很多issue但是没有人回复我。
谢谢！！！&nbsp;


@许迩一世歡颜〆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月23日(星期四) 下午5:41
收件人: ***@***.***&gt;; 
抄送: "@***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [10cl/chatdev] 玩家作为一个非 Agent 角色，本身也可以与 Agent 进行互动，譬如和 Agent 进行对话，Agent 会根据自己的设定对玩家进行回复我想知道想实现这部分功能的代码有哪些可以说下位置在哪么 (Issue #20)





 
我在 generative_agents 看到你也刷了很多ISSUE，看起来你对Github不太熟悉，并且有很多疑问，可以整理一下你的背景和你想了解的内容发送到我的邮箱，我会给你解答，谢谢

**Comment by 10cl** [comment]
先思考你当前想做的事情的目标是什么，从研究原理上而言， 非 Agent 角色在ChatGPT中，你在输入框输入的内容就是这个角色，generative_agents  通过python构建了不同的prompt，直接提取prompt在对话框做模拟就可以了，对于工程效果而言，如果开始没思路，不建议从头研究，在我项目上的PromptIDE中编辑GPTs有没有可能实现你想要的，是否设计接口上有我能做的事情？

**Comment by 2642543078** [comment]
我想要做的就是控制一个非agent进行移动 这个agent移动走到一个agent范围内有个对话框可以进行对话聊天了就是这么一个简单的功能 我的问题是agent移动这部分不知道怎么做 移动以后位置信息怎么传送到后端后端和前端连接这部分不知道怎么做&nbsp;
&nbsp;


@许迩一世歡颜〆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月23日(星期四) 晚上8:50
收件人: ***@***.***&gt;; 
抄送: "@***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [10cl/chatdev] 玩家作为一个非 Agent 角色，本身也可以与 Agent 进行互动，譬如和 Agent 进行对话，Agent 会根据自己的设定对玩家进行回复我想知道想实现这部分功能的代码有哪些可以说下位置在哪么 (Issue #20)





 
先思考你当前想做的事情的目标是什么，从研究原理上而言， 非 Agent 角色在ChatGPT中，你在输入框输入的内容就是这个角色，generative_agents  通过python构建了不同的prompt，直接提取prompt在对话框做模拟就可以了，对于工程效果而言，如果开始没思路，不建议从头研究，在我项目上的PromptIDE中编辑GPTs有没有可能实现你想要的，是否设计接口上有我能做的事情？

**Comment by 2642543078** [comment]
我想要做的就是控制一个非agent进行移动 这个非agent移动走到一个agent范围内有一个对话框可以进行对话聊天了就是这么一个简单的功能 我的问题是agent移动这部分不知道怎么做 移动以后位置信息怎么传送到后端 ，后端和前端连接这部分不知道怎么连接的，就是想要做一个简单游戏可以进行聊天对话的，有个玩家进去可以跟agent进行对话的，因为我不是前端，所以这部分我做不知道怎么做




@许迩一世歡颜〆
***@***.***



&nbsp;

**Comment by 2642543078** [comment]
我想要做的就是控制一个非agent进行移动 这个非agent移动走到一个agent范围内有一个对话框可以进行对话聊天了就是这么一个简单的功能 我的问题是agent移动这部分不知道怎么做 移动以后位置信息怎么传送到后端 ，后端和前端连接这部分不知道怎么连接的，就是想要做一个简单游戏可以进行聊天对话的，有个玩家进去可以跟agent进行对话的，因为我不是前端，所以这部分我做不知道怎么做,如果可以告诉我实现这部分功能的代码位置在哪里也是可以的，非常感谢。




@许迩一世歡颜〆
***@***.***



&nbsp;

**Comment by 2642543078** [comment]
您好，就是我所说的那个问题，那我想知道在项目里实现那一部分的代码在哪里呢，我想要的只是一个复现




@许迩一世歡颜〆
***@***.***



&nbsp;

**Comment by 10cl** [comment]
这里是25个NPC角色生成开始的地方： 
```html
	  for (let i=0; i<Object.keys(spawn_tile_loc).length; i++) { 
	    let persona_name = Object.keys(spawn_tile_loc)[i];
	    let start_pos = [spawn_tile_loc[persona_name][0] * tile_width + tile_width / 2, 
	                     spawn_tile_loc[persona_name][1] * tile_width + tile_width];
	    let new_sprite = this.physics.add
	                         .sprite(start_pos[0], start_pos[1], "atlas", "misa-front")
	                         .setSize(30, 40)
	                         .setOffset(0, 32); // DEBUG 1 --- I added 32 offset on Dec 29. 
	    // Here, we are creating the persona and its pronunciatio sprites.
	    personas[persona_name] = new_sprite;
	    pronunciatios[persona_name] = this.add.text(
	                                   new_sprite.body.x - 6, 
	                                   new_sprite.body.y - 42 - 32, // DEBUG 1 --- I added 32 offset on Dec 29. 
	                                   "🦁", {
	                                   font: "28px monospace", 
	                                   fill: "#000000", 
	                                   padding: { x: 8, y: 8}, 
	                                   backgroundColor: "#ffffff",
	                                   border:"solid",
	                                   borderRadius:"10px"}).setDepth(3);
	  }

```
https://github.com/joonspk-research/generative_agents/blob/c7e0c16d88cba8f3611378bea57dbcac08b9d235//environment/frontend_server/templates/home/main_script.html?#L281-L302
这个部分的代码是新增游戏角色的部分，generative_agents 没有设计非Agent角色，也没有可交互的逻辑，所以你可以尝试在这个地方加入输入框和角色并加入交互逻辑，了解原项目源码的架构并了解一下游戏开发的内容才能完成这样的功能。

**Comment by 2642543078** [comment]
非常感谢 是的我也是找到了这部分的代码 我还是不知道他这个后端前端如何通信 如果要实现交互逻辑是否后端代码都需要大改 感知模块是否都需要改动 这是一个大的工程啊&nbsp;
&nbsp;


@许迩一世歡颜〆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月28日(星期二) 中午11:34
收件人: ***@***.***&gt;; 
抄送: "@***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [10cl/chatdev] 玩家作为一个非 Agent 角色，本身也可以与 Agent 进行互动，譬如和 Agent 进行对话，Agent 会根据自己的设定对玩家进行回复我想知道想实现这部分功能的代码有哪些可以说下位置在哪么 (Issue #20)





 
这里是25个NPC角色生成开始的地方：
 	  for (let i=0; i<Object.keys(spawn_tile_loc).length; i++) {  	    let persona_name = Object.keys(spawn_tile_loc)[i]; 	    let start_pos = [spawn_tile_loc[persona_name][0] * tile_width + tile_width / 2,  	                     spawn_tile_loc[persona_name][1] * tile_width + tile_width]; 	    let new_sprite = this.physics.add 	                         .sprite(start_pos[0], start_pos[1], "atlas", "misa-front") 	                         .setSize(30, 40) 	                         .setOffset(0, 32); // DEBUG 1 --- I added 32 offset on Dec 29.  	    // Here, we are creating the persona and its pronunciatio sprites. 	    personas[persona_name] = new_sprite; 	    pronunciatios[persona_name] = this.add.text( 	                                   new_sprite.body.x - 6,  	                                   new_sprite.body.y - 42 - 32, // DEBUG 1 --- I added 32 offset on Dec 29.  	                                   "🦁", { 	                                   font: "28px monospace",  	                                   fill: "#000000",  	                                   padding: { x: 8, y: 8},  	                                   backgroundColor: "#ffffff", 	                                   border:"solid", 	                                   borderRadius:"10px"}).setDepth(3); 	  }
 
https://github.com/joonspk-research/generative_agents/blob/c7e0c16d88cba8f3611378bea57dbcac08b9d235//environment/frontend_server/templates/home/main_script.html?#L281-L302
 这个部分的代码是新增游戏角色的部分，generative_agents 没有设计非Agent角色，也没有可交互的逻辑，所以你可以尝试在这个地方加入输入框和角色并加入交互逻辑，了解原项目源码的架构并了解一下游戏开发的内容才能完成这样的功能。

**Comment by 10cl** [comment]
```html
	function update(time, delta) {
		// *** SETUP PLAY AND PAUSE BUTTON *** 
		let play_context = this;
		function game_resume() {  
			play_context.scene.resume();
		}  
		play_button.onclick = function(){
			game_resume();
		};
		function game_pause() {  
			play_context.scene.pause();
		}  
		pause_button.onclick = function(){
			game_pause();
		};

	  // *** MOVE CAMERA *** 
	  // This is where we finish up the camera setting we started in the create() 
	  // function. We set the movement speed of the camera and wire up the keys to
	  // map to the actual movement.
	  const camera_speed = 400;
	  // Stop any previous movement from the last frame
	  player.body.setVelocity(0);
	  if (cursors.left.isDown) {
	    player.body.setVelocityX(-camera_speed);
	  } 
	  if (cursors.right.isDown) {
	    player.body.setVelocityX(camera_speed);
	  } 
	  if (cursors.up.isDown) {
	    player.body.setVelocityY(-camera_speed);
	  } 
	  if (cursors.down.isDown) {
	    player.body.setVelocityY(camera_speed);
	  }

	  // console.log("phase: " + phase + ", step: " + step);
	  // *** MOVE PERSONAS ***
	  // Moving personas take place in three distinct phases: "process," "update,"
	  // and "execute." These phases are determined by the value of <phase>. 
	  // Only one of the three phases is incurred in each update cycle. 
	  if (phase == "process") {
	    // "process" takes all current locations of the personas and send them to
	    // the frontend server in a json form. Here, we first create the json 
	    // file that records all persona locations: 
	    let data = {"step": step, 
	    						"sim_code": sim_code,
	                "environment": {}}
	    for (let i=0; i<Object.keys(personas).length; i++) {
	      let persona_name = Object.keys(personas)[i];
	      data["environment"][persona_name] = {"maze": curr_maze,
	                                           "x": Math.ceil((personas[persona_name].body.position.x) / tile_width),
	                                           "y": Math.ceil((personas[persona_name].body.position.y) / tile_width)}
	    }
	    var json = JSON.stringify(data);
	    // We then send this to the frontend server: 
	    var retrieve_xobj = new XMLHttpRequest();
	    retrieve_xobj.overrideMimeType("application/json");
	    retrieve_xobj.open('POST', "{% url 'process_environment' %}", true);
	    retrieve_xobj.send(json);   
	    // Finally, we update the phase variable to start the "udpate" process. 
	    // Now that we sent all persona locations to the backend server, we need
	    // to wait until the backend determines what the personas will do next. 
	    phase = "update";
	  } 

	  else if (phase == "update") { 
	    // Update is where we * wait * for the backend server to finish 
	    // computing about what the personas will do next given their current 
	    // situation. 
	    // We do this by continuously asking the backend server if it is ready. 
	    // The backend server is ready when it returns a json that has a key-val
	    // pair with "<move>": true.
	    // Note that we do not want to overburden the backend too much by 
	    // over-querying; so, we have a timer set so we only query it once every
	    // timer_max cycles. 
	    if (timer <= 0) {
	      var update_xobj = new XMLHttpRequest();
	      update_xobj.overrideMimeType("application/json");
	      update_xobj.open('POST', "{% url 'update_environment' %}", true);
	      update_xobj.addEventListener("load", function() {
	        if (this.readyState === 4) {
	          if (update_xobj.status === 200) {
	            if (JSON.parse(update_xobj.responseText)["<step>"] == step) {
	              execute_movement = JSON.parse(update_xobj.responseText)
	              phase = "execute";
	            }
```
https://github.com/joonspk-research/generative_agents/blob/c7e0c16d88cba8f3611378bea57dbcac08b9d235//environment/frontend_server/templates/home/main_script.html?#L332-L418
update函数每16.7ms执行一次，这里就是交互的逻辑，这里是在循环的POST请求Python接口得到移动数据更新地图： 	     update_xobj.open('POST', "{% url 'update_environment' %}", true);
