### ISSUE TITLE
No overload matches this call

### ISSUE THREAD

**Issue by zwilch** [10cl/chatdev#24]
**Describe the bug**

src/app/state/index.ts:25:31 - error TS2769: No overload matches this call.
in
25 export const licenseKeyAtom = atomWithStorage('licenseKey', '', undefined, { unstable_getOnInit: true })

**Details**
Win10
npm -v
10.2.5 

**Workflow**
V1.3.2 dezip
run npm update
and
run npm run build

**Comment by 10cl** [comment]
node version recommended:  > v18.17.1
