### ISSUE TITLE
Enhancement: detailed view of Agent structure and source code

### ISSUE THREAD

**Issue by zwilch** [10cl/chatdev#27]
In the ACE Editor it would be nice that i can generate a detailed description of the Agent.

Description like this: https://chatdev.toscl.com/s/1702305234ClxC6dYdOu

**Comment by 10cl** [comment]
version >1.3.2, In the ACE Editor, "Upload" Button is  does. After uploading, this link will be generated and displayed in your workspace.

**Comment by zwilch** [comment]
> version >1.3.2, In the ACE Editor, "Upload" Button is does. After uploading, this link will be generated and displayed in your workspace.

sorry my description was not clear enough. It would be helpfull on develepment process to have this summary  on a button without "upload" before.

More in Detail, when I try to build a yaml structure of an special task and develop the different nodes, it would be nice to press a button wich shows this nice summary (may also in a new tab).
