### ISSUE TITLE
Enhancement: Node Flow Control

### ISSUE THREAD

**Issue by zwilch** [10cl/chatdev#28]
Is it possible to change the next node in Javascript.
It would be nice to change the next node to another node.
So we can change the way depends of analysis of output to different tasks.

**Comment by 10cl** [comment]
This is a DAG structure, if the design of such logic will not make the logic confusing?
node `output` variable through the `func` , after js processing to the next node, it should be enough to analysis output.
or you can provide a rough YAML structure that you feel is reasonable, and I can try to design it.

**Comment by zwilch** [comment]
thanks for your response
may you are right its to complicated

I was thinking about some "loops" for trying to make a enhancement process in "X" repetition rounds.
I could implementing loops if i could set in Javascripf Func a counter and change the next node after reaching counter.
In YAML I dont know how to desing it.
