### ISSUE TITLE
How to rebuild this project by python?

### ISSUE THREAD

**Issue by Ottomachine1** [10cl/chatdev#30]

**Comment by Ottomachine1** [comment]
Have you considered using python to reproduce this project? I would be very grateful if you have any help.

**Comment by zwilch** [comment]
@Ottomachine1  may see at this: 
https://github.com/OpenBMB/ChatDev

**Comment by 10cl** [comment]
to make it easier to use and design our agent, I converted to JavaScript,  All in web, if you like python project:
https://github.com/joonspk-research/generative_agents/
