### ISSUE TITLE
src/app/components/Chat/ConversationPanel.tsx

### ISSUE THREAD

**Issue by zwilch** [10cl/chatdev#33]
**Describe the bug**
I tried to fix youtubei and installed "youtubei": "^1.3.3"

npm -v
10.2.5
node -v
v20.10.0

```
git clone https://github.com/10cl/chatdev.git
npm run build

src/app/components/Chat/ConversationPanel.tsx:28:26 - error TS2307: Cannot find module './LocalPrompts' or its corresponding type declarations.

28 import LocalPrompts from './LocalPrompts'

```
and yes the main source (git clone https://github.com/10cl/chatdev.git) try to import a non more existing file "LocalPrompts"

**Comment by 10cl** [comment]
```
import LocalPrompts from '../PromptIDE/LocalPrompts'
```
use the latest code
