### ISSUE TITLE
chatdev1.4.0　大佬老师这个版本在yarn　build时出错：

### ISSUE THREAD

**Issue by ZenXir** [10cl/chatdev#34]
![a9b0fe60-dae5-4814-9226-fc8796172fa8](https://github.com/10cl/chatdev/assets/57025873/ed9b4bff-a340-4009-a7ed-bf7c5f0441d5)
新发布的 1.4.0版本 build出错大佬老师

**Comment by 10cl** [comment]
拉取最新代码试下

**Comment by ZenXir** [comment]
感谢大佬老师，拉取了最新代码build正常了
但在浏览器的extension页面运行时，提示缺少文件，是我的操作不对是吗？
![a9b0fe60-dae5-4814-9226-fc8796172fa8](https://github.com/10cl/chatdev/assets/57025873/2a02ba2d-2694-4727-9097-3ad94ce3272e)

**Comment by 10cl** [comment]
用dist目录

**Comment by ZenXir** [comment]
感谢大佬老师指导
