### ISSUE TITLE
讯飞星火使用不了

### ISSUE THREAD

**Issue by siqiSong** [10cl/chatdev#8]
讯飞星火使用不了，好像没有提示获取权限，有没有考虑用API的形式

**Comment by siqiSong** [comment]
而且在chatgpt的对话框里，依赖chatgpt的上下文机制，不好控制自己的记忆力机制。

**Comment by 10cl** [comment]
> 而且在chatgpt的对话框里，依赖chatgpt的上下文机制，不好控制自己的记忆力机制。

新的大版本已经更新，可以根据需要自定义prompt flow执行流程 以及NPC的角色定义，定义你想要的运行机制，对于Memory这块的设计和展示，这块我还需要想想，如果你有时间的话，可以体验一下给我一些建议。

**Comment by siqiSong** [comment]
我是讯飞开放平台的生态合作经理，方便的话可以加一下我的微信15600647988，我们可以支持一些免费的token

10cl ***@***.***>于2023年9月25日 周一18:13写道：
